# Generated by Django 5.1.7 on 2025-04-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
