# Generated by Django 5.2 on 2025-04-25 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='message',
        ),
    ]
