# Generated by Django 5.2 on 2025-04-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0002_remove_registration_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_address',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_city',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_country',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_guardian_name',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_guardian_occupation',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_guardians_mobile',
            field=models.CharField(default='Not Provided', max_length=15),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_preferred_timings',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_state',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_training_location',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_training_mode',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
        migrations.AddField(
            model_name='registration',
            name='reg_zip',
            field=models.CharField(default='Not Provided', max_length=10),
        ),
    ]
