# Generated by Django 5.2 on 2025-04-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0003_registration_gender_registration_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='course',
        ),
    ]
