# Generated by Django 5.2 on 2025-04-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0004_remove_registration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.CharField(default='Not Provided', max_length=100),
        ),
    ]
