# Generated by Django 5.1.7 on 2025-05-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scope', '0005_registration_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='reg_password',
            field=models.CharField(default='Not Provided', max_length=8),
        ),
    ]
